var Events = {
    EVENT_BUS_CONNECTED: 'EVENT_BUS_CONNECTED',
    EVENT_BUS_DISCONNECTED: 'EVENT_BUS_DISCONNECTED',
    USER_CREATED: 'USER_CREATED',
    USER_UPDATED: 'USER_UPDATED',
    USER_DELETED: 'USER_DELETED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
}

module.exports = Events;